###endpoint
POST http://localhost:8080/reservas
Content-Type: application/json

{
    "id": 1,
    "fecha": "2024-06-01",
    "hora": "19:00",
    "num_personas": 4,
    "cliente_id": 1,
    "mesa_id": 1
}

